# See schema in factory_schema_config_task.py for descriptions of common parameters.

defaults:
    - TacSLBase
    - HydroShearTrainBase
    - _self_

name: BinTaskPacking
physics_engine: ${..physics_engine}

env:
    task_type: insertion #  insertion, placement, screwing
    numEnvs: ${resolve_default:128,${...num_envs}}
    numActions: 6
    franka_urdf_file: 'tacsl_franka_gelsight_mini_box.urdf'
    freespace_dims: [0.23, 0.23, 0.04] # [length, width, height] of bin
    elastomer_resolution: 0.001
    indenter_resolution: 0.001

    friction_insertion_obj: 0.5
    friction_preset_objs: 1.0
    friction_bin: 1.0
    friction_elastomer: 1.0

    compliance_stiffness: 500.0

## domain randomization
randomize:
    franka_arm_initial_dof_pos: [0.0002, -0.1591, 0.0005, -2.0966, -0.0002, 1.9335, 0.7855]
    fingertip_midpoint_pos_initial: [0.5, 0.0, 0.2]  # initial position of midpoint between fingertips above table
    fingertip_midpoint_pos_noise: [0.1, 0.1, 0.05]  # noise on fingertip pos
    fingertip_midpoint_rot_initial: [3.1416, 0, 0.0]  # initial rotation of fingertips (Euler)
    fingertip_midpoint_rot_noise: [0.01, 0.01, 0.01]  # noise on rotation
    insertion_obj_noise_rot_in_gripper: [0.0, 0.0, 0.0]  # noise on plug rotation within gripper, z is along the axis of the gripper can be [-np.pi, np.pi], y is across the axis can be [-np.pi/10, np.pi/10]
    insertion_obj_noise_pos_in_gripper: [0.003, 0.0, 0.006]
    initial_bin_pos: [0.5099, 0.011, 0.0019]  # initial position of bin on table
    initial_bin_rot: [0.0, 0.0, 0.0] # initial rotation of bin on table (euler)
    bin_pos_z_noise: 0.0
    inhand_pos_initial: [0.0, 0.0, 0.015]  # initial position of inhand object
    insertion_obj_inhand_rotation: 0.0  # initial rotation of inhand object (euler in y-direction along grasp)
    insertion_obj_inhand_rotation_noise_range: [0.0, 0.0]

    preset_object_squish_goal: False
    preset_object_randomization: False
    
    
    preset_object_squish_padding: 0.02
    preset_object_squish_noise_range: [0.0, 0.01]
    
    preset_object_squish_vert: False
    preset_object_random_squish_prob: 0.5
    preset_object_use_random_squish_dir: False
    
    preset_object_squish_single: False
    preset_object_use_random_squish_single: False
    preset_object_random_single_squish: 0.5

    preset_object_pos_noise: [0.00, 0.00, 0.00]  # noise on plug position in meters
    preset_object_yaw_noise: 0.0 # noise on plug yaw rotation in degrees
    
## rl algorithm parameters
rl:
    visualize_keypoints: False  # flag to visualize keypoints in the environment
    visualize_packed_keypoints: False # flag to visualize packed object keypoints in the environment
    visualize_goal_pose: False
    close_error_thresh: 0.03  # threshold below which plug is considered close enough to socket/goal, socket depth: 0.0089916
    success_bonus: 0.1  # bonus if plug is close enough to the goal
    contact_penalty_scale: 0.01

    max_episode_length: 256