# See schema in factory_schema_config_task.py for descriptions of common parameters.

defaults:
    - TacSLBase
    - BookTaskShelving
    - _self_

randomize:
    preset_object_squish_goal: True
    preset_object_randomization: True
    preset_object_use_squish_tilt: False
    preset_object_use_random_tilt: True
    preset_object_random_tilt_prob: 0.5
    preset_object_squish_padding: 0.02
    preset_object_squish_noise_range: [-0.005, 0.00]
rl:
    contact_penalty_scale: 0.0